# Generated by Django 3.1.2 on 2020-10-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_name', models.CharField(max_length=255, verbose_name='formation_name')),
                ('num_def', models.IntegerField(verbose_name='number_defenders')),
                ('num_mid', models.IntegerField(verbose_name='number_midfielders')),
                ('num_fwd', models.IntegerField(verbose_name='number_forwards')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_first_name', models.CharField(max_length=255, verbose_name='player_first_name')),
                ('player_last_name', models.CharField(max_length=255, verbose_name='player_last_name')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, unique=True, verbose_name='position_name')),
                ('type', models.CharField(choices=[('Golero', 'Gol'), ('Defensa', 'Def'), ('Mediocampista', 'Med'), ('Delantero', 'Del'), ('Director Tecnico', 'Dir')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.position'),
        ),
    ]
